Bioinformatics Course > First Capstone Project
shahedakhatoon/Bioinformatics-online-courses pull request #1
Opened 2022-03-17 17:39 UTC by shahedakhatoon

## Added the following:
1. Home page
2. About page
3. Presenters section dynamically
4. Configured Linters
5. Designed the UI with CSS.

2022-03-17 20:01 UTC, micheaol requested changes
Hi @shahedakhatoon , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 20:01 UTC, micheaol commented on README.md
> +
Please ensure that the README contains an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-03-17 20:01 UTC, micheaol commented on index.html
> +      </div>
Please ensure that the margin between the cards looks almost identical to the original design according to the requirement.

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/158880610-e63c7f8f-deab-4562-a289-cd8ba95eeb4c.png) | ![image](https://user-images.githubusercontent.com/10332499/158880460-8f3269c7-0ca6-4265-a1c2-d75e3868a844.png)

2022-03-17 20:01 UTC, micheaol commented on index.html
> +    <button class="more-btn" type="button">More <span> <i class="fa fa-angle-down"></i></span></button>
Please ensure that this section uses the exact same background color, borders, etc, which the cards border invisible from the original design.

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/158881455-6a3a33a7-e030-4e09-9a1b-66ce9f59a49b.png) | ![image](https://user-images.githubusercontent.com/10332499/158881334-9c692c41-fc69-4734-9d77-206c1775e21a.png)

2022-03-17 20:01 UTC, micheaol commented on index.html
> +        <div class="program-title"><h3>Networking</h3></div>
Please ensure that the pages should look almost identical to the original design.

Your Implementation | Figma Design
:---:|:---:
![Home_mobile](https://user-images.githubusercontent.com/10332499/158882345-16e145fd-2966-4092-b3a4-cc1ec6929d31.png) | ![image](https://user-images.githubusercontent.com/10332499/158882497-be721588-efe8-42cc-a0c9-5324b59f6271.png)

2022-03-17 20:01 UTC, micheaol commented on index.html
> +        <img class="program-img" src="src/forum.png" alt="Forum">
Please ensure that the pages should look almost identical to the original design.

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/158882767-86cd1687-ee4b-4caa-90e7-ba9c1789e127.png) | ![image](https://user-images.githubusercontent.com/10332499/158882832-9c870146-1d52-46d3-a6e2-38adf8193380.png)

2022-03-17 20:01 UTC, micheaol commented on about.html
> +  <h2 class="lecturerTitle">Bioinformatics Online Course 2022</h2>
Please ensure that your page is responsive according to the requirement.

![image](https://user-images.githubusercontent.com/10332499/158883239-ca976cf5-948c-4cce-be24-6a5157e61a89.png)

2022-03-17 20:01 UTC, micheaol commented on about.html
> +      <div class="layer">
Please ensure that the pages should look almost identical to the original design.

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/158883523-ffbe0ff2-dede-41d1-a5d0-fbcaa8ba6ccb.png) | ![image](https://user-images.githubusercontent.com/10332499/158883620-4fb74b6d-3867-42a8-91ab-d9586910f2c8.png)

2022-03-17 20:01 UTC, micheaol commented on README.md
> +## Live Demo
Please ensure that you make use of GitHub Pages to deploy the web pages according to the project requirement.

2022-03-18 06:30 UTC, shahedakhatoon commented on index.html
> +    <button class="more-btn" type="button">More <span> <i class="fa fa-angle-down"></i></span></button>
@micheaol Please be clear about the word invisible, applying the color swatch #d3d3d3 given in the design doesn't look similar to the lecturers' card in the Figma. In fact, the background color and border that I've used look more similar to the Figma design. Please see the screenshot, after changing background to #d3d3d3, it looks dissimilar.
![127 0 0 1_5500_Bioinformatics-online-courses_](https://user-images.githubusercontent.com/73285210/158949236-e3298b14-5a4a-4d11-b77b-31a7ab847f8d.png)

2022-03-18 06:32 UTC, shahedakhatoon commented on index.html
> +        <div class="program-title"><h3>Networking</h3></div>
@micheaol Please see the changes

![127 0 0 1_5500_Bioinformatics-online-courses_ (1)](https://user-images.githubusercontent.com/73285210/158949431-151bf4f3-c224-482d-9de2-c5ed324acf24.png)

2022-03-18 06:35 UTC, shahedakhatoon commented on about.html
> +  <h2 class="lecturerTitle">Bioinformatics Online Course 2022</h2>
@micheaol Please see the changes I've made. I find he title responsive now

![127 0 0 1_5500_Bioinformatics-online-courses_about html](https://user-images.githubusercontent.com/73285210/158949715-50763f25-d684-4561-9b10-e3329141a05e.png)

2022-03-18 06:44 UTC, shahedakhatoon commented on index.html
> +      </div>
@micheaol Okay! I've removed the gap here, I think it looks exactly the same now. Please see the screenshot.

![127 0 0 1_5500_Bioinformatics-online-courses_index html (2)](https://user-images.githubusercontent.com/73285210/158950689-8b4e6c1f-9960-4fa2-966f-4d8cb1dd84f7.png)

2022-03-18 06:48 UTC, micheaol commented on index.html
> +    <button class="more-btn" type="button">More <span> <i class="fa fa-angle-down"></i></span></button>
@shahedakhatoon 
Thank you for making other changes. To summarize, please make the card the same color as the background to match the original design.

2022-03-18 07:33 UTC, shahedakhatoon commented on index.html
> +        <img class="program-img" src="src/forum.png" alt="Forum">
@micheaol I've made the changes you requested, and I also think the Figma template is that of a Mobile-L view. Please see the screenshot

![127 0 0 1_5500_Bioinformatics-online-courses_index html (3)](https://user-images.githubusercontent.com/73285210/158956682-0adda823-af17-4bf7-8e15-381d6826593a.png)

2022-03-18 07:36 UTC, shahedakhatoon commented on about.html
> +      <div class="layer">
@micheaol I've made the changes you requested.

![127 0 0 1_5500_Bioinformatics-online-courses_about html (1)](https://user-images.githubusercontent.com/73285210/158956896-186359d6-c48e-46fa-a569-8d282f9b464c.png)

2022-03-18 08:34 UTC, shahedakhatoon commented on index.html
> +    <button class="more-btn" type="button">More <span> <i class="fa fa-angle-down"></i></span></button>
@micheaol Okay, thank you. I've set the card the same color as the background,i.e. rgb(247,247,247)

![127 0 0 1_5500_Bioinformatics-online-courses_index html (4)](https://user-images.githubusercontent.com/73285210/158965112-c15132e1-3bcc-4648-89b6-4d3e7fe094af.png)

2022-03-18 09:40 UTC, shahedakhatoon commented on README.md
> +## Live Demo
@micheaol Okay I've deployed on Github pages but the changes I've made did not get deployed

2022-03-18 09:44 UTC, micheaol commented on README.md
> +## Live Demo
@shahedakhatoon 
Please give it some time and check again for the changes.

2022-03-18 09:56 UTC, shahedakhatoon commented on README.md
> +## Live Demo
okay

2022-03-18 10:17 UTC, micheaol approved these changes
# STATUS: APPROVED :green_circle: :clap: 
Hi @shahedakhatoon , 

Great work on making the changes requested by the previous reviewer 👏 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)
Good luck! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 12:39 UTC, merged